extends Reference
class_name EVENT

# Stored here because server/client need to share the same thing
# Won't be able to do so easily in concrete versions of the game app
enum {
	NO_OP
	LOAD_DECK
	DRAW
	OPPONENT_LOAD_DECK
	OPPONENT_DRAW
	SET_TURN_PLAYER
	SET_ACTIVE_PLAYER
	BEGIN_TURN
	END_TURN
	WIN
	LOSE
	DEPLOY
	OPPONENT_DEPLOY
	SET_FACEDOWN
	OPPONENT_SET_FACEDOWN
	CARD_DESTROYED
	OPPONENT_CARD_DESTROYED
	LOSE_LIFE
	OPPONENT_LOSE_LIFE
	ATTACKED_UNIT
	OPPONENT_ATTACKED_UNIT
	READY_CARD
	UNREADY_CARD
	RESPOND_OR_PASS
	ACTIVATE_SKILL
	DISCARD
	OPPONENT_DISCARD
	BOUNCE
	OPPONENT_BOUNCE 
	MILL
	OPPONENT_MILL
	LEGALIZE
	ATTACKED_DIRECTLY
	OPPONENT_ATTACKED_DIRECTLY
	FORBID
	ACTIVATE
	OPPONENT_ACTIVATE
	RESOLVE
	SET_TARGETS
	ATTACK_DECLARED
	AUTO_TARGET
	SET_STATE
	SET_DEPLOYABLE
	SET_SETTABLE
	SET_ACTIVATABLE
}
